### ISSUE TITLE
哥们，clone下来后弄了半天也没编译成功，Android Studio项目怎么连个setting.gradle都没有呢，后来加上了也不行，根本不能运行

### ISSUE THREAD

**Issue by gaoleicoding** [SupLuo/Easy#1]
哥们，clone下来后弄了半天也没编译成功，Android Studio项目怎么连个setting.gradle都没有呢

**Comment by uni-cstar** [comment]
setting.gradle文件提交上来了。

**Comment by uni-cstar** [comment]
工程是能够运行的哈，只不过demo我只是随便写写，没有去详细的介绍功能。具体功能你可以见wiki介绍，目前这个库一直在使用状态，也就是在我们公司的产品中使用着的，所以目前也没遇到什么问题。
