### ISSUE TITLE
对于style的解析似乎有点问题。

### ISSUE THREAD

**Issue by Rickyhohohey** [SupLuo/Easy#2]
你好，SkinFactory里面
 if ("style".equals(attrName)) {//style 属性 eg:style="@style/textStyle"
这边如果是style， attrValue都是诸如「@2131099680」的格式
于是
String styleName = attrValue.substring(attrValue.indexOf("/") + 1);//eg: textStyle
int styleID = context.getResources().getIdentifier(styleName, "style", context.getPackageName());  
这两行解析出来的styleId永远是0，，后面就都不执行了，实际上styleId就已经前面的attrValue里的值了。

这个问题是bug吗，还是是sdk版本差异的原因之类的。。

**Comment by uni-cstar** [comment]
style属性中，目前只支持几个常规的属性，比如textColor，background等，具体我有时间看看

**Comment by uni-cstar** [comment]
```
//处理样式
            if ("style".equals(attrName)) {//style 属性 eg:style="@style/textStyle"
            }
            //如果是支持的属性，并且属性值是引用。 eg: android:background="@drawable/launcher"
            if (SkinAttrSupport.isSupportedAttr(attrName) && attrValue.startsWith("@")) {
            }
```
你说的这个不是问题，SkinFactory的这个方法分为两部分，第一部分是处理style类型的属性值（比如处理@style/textStyle），第二部分是处理直接引用的属性值(比如@color/black)。请注意看源码。
而你说的诸如「@2131099680」的格式的attrValue，则是有第二部分处理，上面代码的第二个if部分判断处理。
